-- ═══════════════════════════════════════════════════════════════════════════
-- Wild Rift Draft — Complete Champion Roster
-- Patch: 7.1f (May 27, 2026) — Current live patch
-- Source: official Wild Rift champion list (113 champions)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO public.champions (slug, name, roles, damage_type, engage_type, difficulty, patch_version, metadata) VALUES

-- ─── SUPPORT ─────────────────────────────────────────────────────────────────
('thresh',      'Thresh',        '{support}',         'magic',    '{engage,peel,utility}',  'hard',   '7.1f', '{"title":"The Chain Warden","tags":["hook","lantern","flay","cc-heavy"]}'),
('lulu',        'Lulu',          '{support}',         'magic',    '{peel,utility}',         'medium', '7.1f', '{"title":"The Fae Sorceress","tags":["polymorph","shield","hypercarry-enabler"]}'),
('blitzcrank',  'Blitzcrank',    '{support}',         'magic',    '{engage,utility}',       'easy',   '7.1f', '{"title":"The Great Steam Golem","tags":["hook","silence","all-in"]}'),
('nami',        'Nami',          '{support}',         'magic',    '{heal,poke,utility}',    'medium', '7.1f', '{"title":"The Tidecaller","tags":["heal","cc","sustain","poke"]}'),
('janna',       'Janna',         '{support}',         'magic',    '{peel,heal,utility}',    'hard',   '7.1f', '{"title":"The Storm''s Fury","tags":["disengage","shield","knock-up"]}'),
('soraka',      'Soraka',        '{support}',         'magic',    '{heal,peel}',            'easy',   '7.1f', '{"title":"The Starchild","tags":["global-heal","sustain","silence"]}'),
('leona',       'Leona',         '{support}',         'magic',    '{engage,utility}',       'easy',   '7.1f', '{"title":"The Radiant Dawn","tags":["hard-engage","stun","tank"]}'),
('alistar',     'Alistar',       '{support}',         'magic',    '{engage,peel,utility}',  'medium', '7.1f', '{"title":"The Minotaur","tags":["knock-up","headbutt","tank"]}'),
('braum',       'Braum',         '{support}',         'physical', '{peel,engage,utility}',  'easy',   '7.1f', '{"title":"The Heart of the Freljord","tags":["wall","passive-stun","tank"]}'),
('senna',       'Senna',         '{support,dragon}',  'physical', '{peel,utility,carry}',   'medium', '7.1f', '{"title":"The Redeemer","tags":["global-ult","heal","souls"]}'),
('seraphine',   'Seraphine',     '{support,mid}',     'magic',    '{poke,heal,utility}',    'easy',   '7.1f', '{"title":"The Starry-Eyed Songstress","tags":["mass-cc","heal","enchanter"]}'),
('rakan',       'Rakan',         '{support}',         'magic',    '{engage,peel,utility}',  'medium', '7.1f', '{"title":"The Charmer","tags":["engage","charm","dash"]}'),
('karma',       'Karma',         '{support,mid}',     'magic',    '{poke,utility,peel}',    'medium', '7.1f', '{"title":"The Enlightened One","tags":["shield","root","mantra"]}'),
('zyra',        'Zyra',          '{support,mid}',     'magic',    '{poke,engage,utility}',  'medium', '7.1f', '{"title":"Rise of the Thorns","tags":["plants","aoe","zone-control"]}'),
('lux',         'Lux',           '{support,mid}',     'magic',    '{poke,utility}',         'easy',   '7.1f', '{"title":"The Lady of Luminosity","tags":["root","shield","burst"]}'),
('pyke',        'Pyke',          '{support}',         'physical', '{engage,utility}',       'medium', '7.1f', '{"title":"The Bloodharbor Ripper","tags":["hook","execute","roam"]}'),
('sona',        'Sona',          '{support}',         'magic',    '{heal,poke,utility}',    'easy',   '7.1f', '{"title":"Maven of the Strings","tags":["heal","speed-boost","sustain"]}'),
('yuumi',       'Yuumi',         '{support}',         'magic',    '{heal,peel,utility}',    'easy',   '7.1f', '{"title":"The Magical Cat","tags":["attach","heal","untargetable"]}'),
('nautilus',    'Nautilus',      '{support,jungle}',  'magic',    '{engage,utility}',       'easy',   '7.1f', '{"title":"The Titan of the Depths","tags":["hook","aoe-cc","tank"]}'),
('galio',       'Galio',         '{support,mid}',     'magic',    '{engage,peel,utility}',  'medium', '7.1f', '{"title":"The Colossus","tags":["global-ult","taunt","shield"]}'),
('milio',       'Milio',         '{support}',         'magic',    '{heal,peel,utility}',    'medium', '7.1f', '{"title":"The Gentle Flame","tags":["cleanse","shield","heal"]}'),
('norra',       'Norra',         '{support}',         'magic',    '{utility,poke}',         'hard',   '7.1f', '{"title":"","tags":["portal","summon","zone-control"],"patch_note":"Nerfed 7.1f — Q and ult damage reduced"}'),
('rell',        'Rell',          '{support}',         'magic',    '{engage,utility}',       'medium', '7.1f', '{"title":"The Iron Maiden","tags":["hard-engage","aoe-cc","tank"]}'),
('swain',       'Swain',         '{support,mid}',     'magic',    '{engage,utility,carry}', 'medium', '7.1f', '{"title":"The Noxian Grand General","tags":["hook","drain","aoe-ult"]}'),
('morgana',     'Morgana',       '{support,mid}',     'magic',    '{utility,engage}',       'easy',   '7.1f', '{"title":"The Fallen","tags":["root","black-shield","aoe-stun"]}'),
('brand',       'Brand',         '{support,mid}',     'magic',    '{poke,engage}',          'medium', '7.1f', '{"title":"The Burning Vengeance","tags":["bouncing-ult","burst","poke"]}'),
('xerath',      'Xerath',        '{support,mid}',     'magic',    '{poke,utility}',         'medium', '7.1f', '{"title":"The Magus Ascendant","tags":["long-range","poke","global-ult"]}'),
('zilean',      'Zilean',        '{support,mid}',     'magic',    '{utility,peel}',         'hard',   '7.1f', '{"title":"The Chronokeeper","tags":["revive-ult","slow","time-warp"]}'),
('vel-koz',     'Vel''Koz',      '{support,mid}',     'magic',    '{poke,utility}',         'medium', '7.1f', '{"title":"The Eye of the Void","tags":["true-damage","poke","laser"]}'),
('annie',       'Annie',         '{support,mid}',     'magic',    '{engage,utility}',       'easy',   '7.1f', '{"title":"The Dark Child","tags":["tibbers","stun","burst"]}'),
('bard',        'Bard',          '{support}',         'magic',    '{utility,peel,engage}',  'hard',   '7.1f', '{"title":"The Wandering Caretaker","tags":["roam","stun","heal-chimes","global-presence"]}'),
('mel',         'Mel',           '{support,mid}',     'magic',    '{poke,utility}',         'medium', '7.1f', '{"title":"","tags":["reflect","shield","poke"]}'),
('shen',        'Shen',          '{support,baron}',   'physical', '{utility,peel,engage}',  'medium', '7.1f', '{"title":"The Eye of Twilight","tags":["taunt","shield","global-ult"],"patch_note":"Buffed 7.1f — base damage up"}'),
('amumu',       'Amumu',         '{jungle,support}',  'magic',    '{engage,utility}',       'easy',   '7.1f', '{"title":"The Sad Mummy","tags":["aoe-stun","hook","tank"]}'),
('ashe',        'Ashe',          '{dragon,support}',  'physical', '{utility,carry,poke}',   'easy',   '7.1f', '{"title":"The Frost Archer","tags":["global-stun","slow","vision"]}'),
('malphite',    'Malphite',      '{baron,support}',   'magic',    '{engage,utility}',       'easy',   '7.1f', '{"title":"Shard of the Monolith","tags":["aoe-engage","unstoppable","tank"]}'),

-- ─── JUNGLE ──────────────────────────────────────────────────────────────────
('lee-sin',     'Lee Sin',       '{jungle}',          'physical', '{engage,utility}',       'hard',   '7.1f', '{"title":"The Blind Monk","tags":["insec","skill-shot","mobile"]}'),
('vi',          'Vi',            '{jungle}',          'physical', '{engage,utility}',       'medium', '7.1f', '{"title":"The Piltover Enforcer","tags":["single-target-engage","lock-down"]}'),
('xin-zhao',    'Xin Zhao',      '{jungle}',          'physical', '{engage}',               'easy',   '7.1f', '{"title":"Seneschal of Demacia","tags":["early-game","all-in","knock-up"]}'),
('graves',      'Graves',        '{jungle}',          'physical', '{carry}',                'medium', '7.1f', '{"title":"The Outlaw","tags":["burst","shotgun","carry"]}'),
('hecarim',     'Hecarim',       '{jungle}',          'physical', '{engage}',               'medium', '7.1f', '{"title":"The Shadow of War","tags":["speed","knock-up","fear"]}'),
('evelynn',     'Evelynn',       '{jungle}',          'magic',    '{engage,carry}',         'hard',   '7.1f', '{"title":"Agony''s Embrace","tags":["stealth","assassin","execute"]}'),
('jarvan-iv',   'Jarvan IV',     '{jungle,baron}',    'physical', '{engage,utility}',       'medium', '7.1f', '{"title":"The Exemplar of Demacia","tags":["flag-and-drag","knock-up","wall"]}'),
('kha-zix',     'Kha''Zix',      '{jungle}',          'physical', '{engage,carry}',         'medium', '7.1f', '{"title":"The Voidreaver","tags":["isolated-target","assassin","evolve"]}'),
('kayn',        'Kayn',          '{jungle}',          'physical', '{engage,carry}',         'medium', '7.1f', '{"title":"The Shadow Reaper","tags":["form-choice","wall-walk","transform"]}'),
('viego',       'Viego',         '{jungle}',          'physical', '{engage,carry}',         'hard',   '7.1f', '{"title":"The Ruined King","tags":["possession","reset","carry"],"patch_note":"Nerfed 7.1f — Q heal reduced, R radius tightened"}'),
('nunu',        'Nunu & Willump','{jungle}',          'magic',    '{engage,utility}',       'easy',   '7.1f', '{"title":"The Boy and His Yeti","tags":["snowball","gank","tank"]}'),
('skarner',     'Skarner',       '{jungle}',          'physical', '{engage,utility}',       'medium', '7.1f', '{"title":"The Primordial Sovereign","tags":["suppression","drag","tank"]}'),
('master-yi',   'Master Yi',     '{jungle}',          'physical', '{carry}',                'easy',   '7.1f', '{"title":"The Wuju Bladesman","tags":["alpha-strike","meditate","carry"]}'),
('rengar',      'Rengar',        '{jungle,baron}',    'physical', '{engage,carry}',         'hard',   '7.1f', '{"title":"The Pridestalker","tags":["stealth","burst","assassin"]}'),
('olaf',        'Olaf',          '{jungle,baron}',    'physical', '{carry,engage}',         'easy',   '7.1f', '{"title":"The Berserker","tags":["unstoppable","cc-immune","lifesteal"]}'),
('shyvana',     'Shyvana',       '{jungle}',          'mixed',    '{engage,carry}',         'medium', '7.1f', '{"title":"The Half-Dragon","tags":["dragon-form","tanky-carry","aoe"]}'),
('taliyah',     'Taliyah',       '{jungle,mid}',      'magic',    '{engage,carry}',         'hard',   '7.1f', '{"title":"The Stoneweaver","tags":["wall","wave-clear","burst"],"patch_note":"Nerfed 7.1f — Q,W,E damage all reduced"}'),
('fiddlesticks','Fiddlesticks',  '{jungle}',          'magic',    '{engage,carry}',         'hard',   '7.1f', '{"title":"The Ancient Fear","tags":["aoe-fear","scarecrow","global-ult"]}'),
('kindred',     'Kindred',       '{jungle}',          'physical', '{poke,carry}',           'medium', '7.1f', '{"title":"The Eternal Hunters","tags":["mark","zone-control","late-game"]}'),
('lillia',      'Lillia',        '{jungle,mid}',      'magic',    '{poke,carry}',           'medium', '7.1f', '{"title":"The Bashful Bloom","tags":["sleepy-dust","aoe","wave-clear"]}'),
('nidalee',     'Nidalee',       '{jungle}',          'magic',    '{poke,carry}',           'hard',   '7.1f', '{"title":"The Bestial Huntress","tags":["form-shift","spear","early-pressure"]}'),
('nocturne',    'Nocturne',      '{jungle}',          'physical', '{engage,carry}',         'medium', '7.1f', '{"title":"The Eternal Nightmare","tags":["fear-ult","global-ult","assassin"]}'),
('poppy',       'Poppy',         '{jungle,baron}',    'physical', '{engage,utility}',       'medium', '7.1f', '{"title":"Keeper of the Hammer","tags":["wall-stun","anti-dash","tank"]}'),
('rammus',      'Rammus',        '{jungle}',          'physical', '{engage,utility}',       'easy',   '7.1f', '{"title":"The Armordillo","tags":["taunt","tank","armor-stack"]}'),
('volibear',    'Volibear',      '{baron,jungle}',    'mixed',    '{engage,utility}',       'medium', '7.1f', '{"title":"The Relentless Storm","tags":["cc","disable-turrets","tanky-carry"]}'),
('warwick',     'Warwick',       '{jungle}',          'physical', '{engage,carry}',         'easy',   '7.1f', '{"title":"The Uncaged Wrath of Zaun","tags":["heal","suppress-ult","lifesteal"]}'),
('camille',     'Camille',       '{baron,jungle}',    'physical', '{engage}',               'hard',   '7.1f', '{"title":"The Steel Shadow","tags":["hookshot","prison","mobile"]}'),
('gragas',      'Gragas',        '{baron,jungle,mid}','magic',    '{engage,peel,utility}',  'medium', '7.1f', '{"title":"The Rabble Rouser","tags":["barrel","knock-back","playmaker"],"patch_note":"Nerfed 7.1f — W damage rebalanced"}'),
('jax',         'Jax',           '{baron,jungle}',    'mixed',    '{engage,carry}',         'medium', '7.1f', '{"title":"Grandmaster at Arms","tags":["counter-strike","1v1","late-game"]}'),

-- ─── MID ─────────────────────────────────────────────────────────────────────
('syndra',      'Syndra',        '{mid}',             'magic',    '{poke,engage}',          'hard',   '7.1f', '{"title":"The Dark Sovereign","tags":["burst","cc","execute"]}'),
('orianna',     'Orianna',       '{mid}',             'magic',    '{utility,engage,poke}',  'hard',   '7.1f', '{"title":"The Lady of Clockwork","tags":["ball","cc","zone-control"]}'),
('zed',         'Zed',           '{mid}',             'physical', '{engage}',               'hard',   '7.1f', '{"title":"The Master of Shadows","tags":["assassin","burst","shadow"]}'),
('akali',       'Akali',         '{mid,baron}',       'magic',    '{engage}',               'hard',   '7.1f', '{"title":"The Rogue Assassin","tags":["assassin","mobile","shroud"]}'),
('ahri',        'Ahri',          '{mid}',             'magic',    '{engage,poke}',          'medium', '7.1f', '{"title":"The Nine-Tailed Fox","tags":["charm","triple-dash","roam"]}'),
('yasuo',       'Yasuo',         '{mid,baron}',       'physical', '{engage,carry}',         'hard',   '7.1f', '{"title":"The Unforgiven","tags":["wind-wall","carry","mobile"]}'),
('twisted-fate','Twisted Fate',  '{mid}',             'mixed',    '{utility,engage}',       'hard',   '7.1f', '{"title":"The Card Master","tags":["global-ult","gold-card","roam"]}'),
('katarina',    'Katarina',      '{mid}',             'magic',    '{engage,carry}',         'hard',   '7.1f', '{"title":"The Sinister Blade","tags":["reset","no-resource","mobile"]}'),
('vex',         'Vex',           '{mid}',             'magic',    '{engage,carry}',         'medium', '7.1f', '{"title":"The Gloomist","tags":["fear","engage","anti-dash"]}'),
('fizz',        'Fizz',          '{mid}',             'magic',    '{engage}',               'hard',   '7.1f', '{"title":"The Tidal Trickster","tags":["untargetable","cc","assassin"]}'),
('kassadin',    'Kassadin',      '{mid}',             'magic',    '{engage}',               'hard',   '7.1f', '{"title":"The Void Walker","tags":["late-game","riftwalk","anti-magic"]}'),
('akshan',      'Akshan',        '{mid,dragon}',      'physical', '{poke,carry}',           'medium', '7.1f', '{"title":"The Rogue Sentinel","tags":["stealth","revive-ally","mobile"],"patch_note":"Buffed 7.1f — Q damage up"}'),
('aurelion-sol','Aurelion Sol',  '{mid}',             'magic',    '{poke,carry}',           'hard',   '7.1f', '{"title":"The Star Forger","tags":["orbit","stun","scaling"]}'),
('aurora',      'Aurora',        '{mid,baron}',       'magic',    '{poke,carry}',           'medium', '7.1f', '{"title":"The Witch Between Worlds","tags":["spirit-realm","poke","mobile"]}'),
('diana',       'Diana',         '{jungle,mid}',      'magic',    '{engage,carry}',         'medium', '7.1f', '{"title":"Scorn of the Moon","tags":["aoe-pull","burst","engage"]}'),
('ekko',        'Ekko',          '{jungle,mid}',      'magic',    '{engage,carry}',         'hard',   '7.1f', '{"title":"The Boy Who Shattered Time","tags":["rewind","stun","mobile"]}'),
('heimerdinger','Heimerdinger',  '{mid,baron}',       'magic',    '{poke,utility}',         'medium', '7.1f', '{"title":"The Revered Inventor","tags":["turrets","zone-control","poke"]}'),
('kennen',      'Kennen',        '{baron,mid}',       'magic',    '{engage,carry}',         'medium', '7.1f', '{"title":"The Heart of the Tempest","tags":["aoe-stun","mobile","teamfight"]}'),
('lissandra',   'Lissandra',     '{mid}',             'magic',    '{engage,utility}',       'medium', '7.1f', '{"title":"The Ice Witch","tags":["self-stasis","root","cc"]}'),
('veigar',      'Veigar',        '{mid}',             'magic',    '{poke,engage}',          'medium', '7.1f', '{"title":"The Tiny Master of Evil","tags":["stack-ap","cage","execute"]}'),
('viktor',      'Viktor',        '{mid}',             'magic',    '{poke,utility}',         'hard',   '7.1f', '{"title":"The Machine Herald","tags":["zone-control","gravity-field","scaling"]}'),
('vladimir',    'Vladimir',      '{mid,baron}',       'magic',    '{poke,carry}',           'medium', '7.1f', '{"title":"The Crimson Reaper","tags":["sustain","pool","scaling"]}'),
('ziggs',       'Ziggs',         '{mid}',             'magic',    '{poke,carry}',           'medium', '7.1f', '{"title":"The Hexplosives Expert","tags":["aoe-poke","wave-clear","siege"]}'),
('zoe',         'Zoe',           '{mid}',             'magic',    '{poke,engage}',          'hard',   '7.1f', '{"title":"The Aspect of Twilight","tags":["sleep","spell-steal","poke"]}'),
('ryze',        'Ryze',          '{mid}',             'magic',    '{utility,carry}',        'hard',   '7.1f', '{"title":"The Rune Mage","tags":["root","scaling","combo-spells"]}'),

-- ─── BARON LANE (Top) ─────────────────────────────────────────────────────────
('darius',      'Darius',        '{baron}',           'physical', '{engage}',               'easy',   '7.1f', '{"title":"The Hand of Noxus","tags":["bleed","execute","bully"]}'),
('fiora',       'Fiora',         '{baron}',           'physical', '{carry,engage}',         'hard',   '7.1f', '{"title":"The Grand Duelist","tags":["riposte","vital","duelist"]}'),
('garen',       'Garen',         '{baron}',           'physical', '{engage}',               'easy',   '7.1f', '{"title":"The Might of Demacia","tags":["execute","silence","sustain"]}'),
('aatrox',      'Aatrox',        '{baron}',           'physical', '{engage,carry}',         'medium', '7.1f', '{"title":"The World Ender","tags":["sustain","cc","revive"]}'),
('renekton',    'Renekton',      '{baron}',           'physical', '{engage}',               'medium', '7.1f', '{"title":"The Butcher of the Sands","tags":["fury","stun","dash"]}'),
('nasus',       'Nasus',         '{baron}',           'physical', '{carry}',                'easy',   '7.1f', '{"title":"The Curator of the Sands","tags":["stack","wither","scaling"]}'),
('k-sante',     'K''Sante',      '{baron}',           'physical', '{engage,peel,utility}',  'hard',   '7.1f', '{"title":"The Pride of Nazumah","tags":["tank","cc","engage"],"patch_note":"Nerfed 7.1f — ult drawbacks increased"}'),
('irelia',      'Irelia',        '{baron,mid}',       'physical', '{engage,carry}',         'hard',   '7.1f', '{"title":"The Blade Dancer","tags":["reset","stun","mobile"]}'),
('tryndamere',  'Tryndamere',    '{baron}',           'physical', '{carry}',                'easy',   '7.1f', '{"title":"The Barbarian King","tags":["undying","crit","split-push"]}'),
('ambessa',     'Ambessa',       '{baron}',           'physical', '{engage,carry}',         'medium', '7.1f', '{"title":"The Matriarch of War","tags":["shield","execute","mobile"],"patch_note":"Adjusted 7.1f — shield base lowered, scaling raised"}'),
('gnar',        'Gnar',          '{baron}',           'mixed',    '{engage,carry}',         'hard',   '7.1f', '{"title":"The Missing Link","tags":["form-shift","poke","engage"]}'),
('gwen',        'Gwen',          '{baron}',           'magic',    '{carry,engage}',         'medium', '7.1f', '{"title":"The Hallowed Seamstress","tags":["true-damage","mist","duelist"]}'),
('mordekaiser', 'Mordekaiser',   '{baron}',           'magic',    '{carry,engage}',         'medium', '7.1f', '{"title":"The Iron Revenant","tags":["isolate-ult","1v1","sustain"]}'),
('ornn',        'Ornn',          '{baron}',           'magic',    '{engage,utility}',       'medium', '7.1f', '{"title":"The Fire below the Mountain","tags":["upgrade-items","cc","tank"]}'),
('pantheon',    'Pantheon',      '{baron,support}',   'physical', '{engage,carry}',         'medium', '7.1f', '{"title":"The Unbreakable Spear","tags":["global-ult","engage","crit"]}'),
('riven',       'Riven',         '{baron}',           'physical', '{engage,carry}',         'hard',   '7.1f', '{"title":"The Exile","tags":["mobile","burst","stun"]}'),
('rumble',      'Rumble',        '{baron}',           'magic',    '{engage,carry}',         'medium', '7.1f', '{"title":"The Mechanized Menace","tags":["aoe-ult","heat-gauge","zone-control"]}'),
('sett',        'Sett',          '{baron}',           'physical', '{engage,carry}',         'easy',   '7.1f', '{"title":"The Boss","tags":["grab","tanky-carry","brawler"]}'),
('sion',        'Sion',          '{baron}',           'physical', '{engage,utility}',       'medium', '7.1f', '{"title":"The Undead Juggernaut","tags":["undying","aoe-stun","tank"]}'),
('teemo',       'Teemo',         '{baron}',           'magic',    '{poke,carry}',           'medium', '7.1f', '{"title":"The Swift Scout","tags":["stealth","poison-traps","poke"]}'),
('urgot',       'Urgot',         '{baron}',           'physical', '{engage,carry}',         'medium', '7.1f', '{"title":"The Dreadnought","tags":["execute-ult","tanky-carry","zone-control"]}'),
('wukong',      'Wukong',        '{baron,jungle}',    'physical', '{engage,carry}',         'medium', '7.1f', '{"title":"The Monkey King","tags":["aoe-engage","clone","spin"]}'),
('yone',        'Yone',          '{baron,mid}',       'mixed',    '{engage,carry}',         'hard',   '7.1f', '{"title":"The Unforgotten","tags":["knock-up","mobile","hybrid-dmg"]}'),
('shen',        'Shen',          '{baron,support}',   'physical', '{utility,peel,engage}',  'medium', '7.1f', '{"title":"The Eye of Twilight","tags":["taunt","shield","global-ult"]}'),
('volibear',    'Volibear',      '{baron,jungle}',    'mixed',    '{engage,utility}',       'medium', '7.1f', '{"title":"The Relentless Storm","tags":["cc","disable-turrets","tanky-carry"]}'),

-- ─── DRAGON LANE (ADC) ───────────────────────────────────────────────────────
('jinx',        'Jinx',          '{dragon}',          'physical', '{carry}',                'easy',   '7.1f', '{"title":"The Loose Cannon","tags":["reset","hyper-carry","global-ult"]}'),
('caitlyn',     'Caitlyn',       '{dragon}',          'physical', '{poke,carry}',           'medium', '7.1f', '{"title":"The Sheriff of Piltover","tags":["range","poke","traps"]}'),
('ezreal',      'Ezreal',        '{dragon,mid}',      'physical', '{poke,carry}',           'medium', '7.1f', '{"title":"The Prodigal Explorer","tags":["blink","skill-shot","safe"]}'),
('miss-fortune','Miss Fortune',  '{dragon}',          'physical', '{poke,carry}',           'easy',   '7.1f', '{"title":"The Bounty Hunter","tags":["bullet-time","poke","cc-ult"]}'),
('jhin',        'Jhin',          '{dragon}',          'physical', '{poke,carry}',           'medium', '7.1f', '{"title":"The Virtuoso","tags":["four-shots","cc","execute"]}'),
('vayne',       'Vayne',         '{dragon,baron}',    'physical', '{carry}',                'hard',   '7.1f', '{"title":"The Night Hunter","tags":["true-damage","stealth","hypercarry"]}'),
('lucian',      'Lucian',        '{dragon,mid}',      'physical', '{poke,carry}',           'medium', '7.1f', '{"title":"The Purifier","tags":["mobile","dash","early-game"]}'),
('kai-sa',      'Kai''Sa',       '{dragon}',          'mixed',    '{carry}',                'hard',   '7.1f', '{"title":"Daughter of the Void","tags":["evolve","stealth","mobile"]}'),
('xayah',       'Xayah',         '{dragon}',          'physical', '{carry,peel}',           'medium', '7.1f', '{"title":"The Rebel","tags":["feathers","root","rakan-synergy"]}'),
('tristana',    'Tristana',      '{dragon}',          'physical', '{carry,engage}',         'easy',   '7.1f', '{"title":"The Yordle Gunner","tags":["jump","reset","tower-push"]}'),
('varus',       'Varus',         '{dragon,mid}',      'mixed',    '{poke,utility}',         'medium', '7.1f', '{"title":"The Arrow of Retribution","tags":["poke","root","chain-cc"]}'),
('draven',      'Draven',        '{dragon}',          'physical', '{carry}',                'hard',   '7.1f', '{"title":"The Glorious Executioner","tags":["gold","axes","snowball"]}'),
('kog-maw',     'Kog''Maw',      '{dragon}',          'mixed',    '{poke,carry}',           'medium', '7.1f', '{"title":"The Mouth of the Abyss","tags":["range","void-ooze","late-game"],"patch_note":"Nerfed 7.1f — W max-health damage reduced"}'),
('samira',      'Samira',        '{dragon}',          'physical', '{engage,carry}',         'hard',   '7.1f', '{"title":"The Desert Rose","tags":["style","aoe-ult","anti-projectile"]}'),
('nilah',       'Nilah',         '{dragon}',          'physical', '{engage,carry}',         'hard',   '7.1f', '{"title":"The Joy Unbound","tags":["melee-adc","enchanter-synergy","aoe"]}'),
('smolder',     'Smolder',       '{dragon}',          'mixed',    '{poke,carry}',           'medium', '7.1f', '{"title":"The Fiery Fledgling","tags":["stack","execute","scaling"]}'),
('zeri',        'Zeri',          '{dragon}',          'physical', '{carry}',                'hard',   '7.1f', '{"title":"The Spark of Zaun","tags":["mobile","wall-ride","hypercarry"]}'),
('sivir',       'Sivir',         '{dragon}',          'physical', '{poke,carry}',           'easy',   '7.1f', '{"title":"The Battle Mistress","tags":["wave-clear","spell-shield","aoe"]}'),
('kalista',     'Kalista',       '{dragon}',          'physical', '{poke,carry}',           'hard',   '7.1f', '{"title":"The Spear of Vengeance","tags":["hop","oath","skill-floor"]}'),
('twitch',      'Twitch',        '{dragon}',          'physical', '{carry}',                'hard',   '7.1f', '{"title":"The Renegade","tags":["stealth","hyper-carry","aoe-ult"]}'),
('corki',       'Corki',         '{dragon,mid}',      'mixed',    '{poke,carry}',           'medium', '7.1f', '{"title":"The Daring Bombardier","tags":["true-damage","poke","wave-clear"]}'),
('kayle',       'Kayle',         '{baron,dragon}',    'mixed',    '{carry}',                'medium', '7.1f', '{"title":"The Righteous","tags":["scaling","ranged-transform","late-game"],"patch_note":"Buffed 7.1f — base AD and mana regen up, heal scaling improved"}'),
('talon',       'Talon',         '{mid,baron}',       'physical', '{engage,carry}',         'medium', '7.1f', '{"title":"The Blade''s Shadow","tags":["assassin","wall-jump","execute"]}'),
('singed',      'Singed',        '{baron}',           'magic',    '{utility,engage}',       'medium', '7.1f', '{"title":"The Mad Chemist","tags":["fling","kite","tank"]}'),
('vladimir',    'Vladimir',      '{mid,baron}',       'magic',    '{poke,carry}',           'medium', '7.1f', '{"title":"The Crimson Reaper","tags":["sustain","pool","scaling"]}')

ON CONFLICT (slug) DO UPDATE SET
  name        = EXCLUDED.name,
  roles       = EXCLUDED.roles,
  damage_type = EXCLUDED.damage_type,
  engage_type = EXCLUDED.engage_type,
  difficulty  = EXCLUDED.difficulty,
  patch_version = EXCLUDED.patch_version,
  metadata    = EXCLUDED.metadata,
  updated_at  = NOW();


-- ═══════════════════════════════════════════════════════════════════════════
-- SYNERGIES (Patch 7.1f) — unchanged set, still valid for current patch
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO public.synergies (champion_a_id, champion_b_id, score, reason, patch_version)
SELECT a.id, b.id, s.score, s.reason, '7.1f'
FROM (VALUES
  ('leona',        'miss-fortune', 92, 'Leona CC chain into MF Bullet Time is a guaranteed teamfight win. Both hit power at level 6 simultaneously.'),
  ('leona',        'jinx',         80, 'Leona locks down targets, letting Jinx freely stack Switcheroo and fish for resets.'),
  ('leona',        'tristana',     82, 'Leona''s multi-CC stops targets for Tristana to burst down with E stacks.'),
  ('thresh',       'jinx',         88, 'Thresh lantern rescues diving Jinx; his hooks open kill windows for her reset pattern.'),
  ('thresh',       'ezreal',       72, 'Thresh provides CC and peel Ezreal needs to stay safe while poking.'),
  ('thresh',       'xayah',        80, 'Thresh lantern lets Xayah escape; his hooks set up her feather combos.'),
  ('lulu',         'vayne',        96, 'S-tier synergy. Polymorph, shield, ult knockup directly fix all of Vayne''s weaknesses.'),
  ('lulu',         'jinx',         88, 'Lulu Whimsy lets Jinx stack freely. Ult saves Jinx from dives and resets.'),
  ('lulu',         'tristana',     85, 'Lulu''s ult knockup pairs with Tristana jump for a double engage layered combo.'),
  ('lulu',         'kai-sa',       88, 'Lulu makes Kai''Sa unkillable through engage while she evolves and assassinates.'),
  ('janna',        'vayne',        90, 'Janna disengage keeps Vayne alive indefinitely. Shield amplifies her attack speed.'),
  ('janna',        'jinx',         82, 'Janna tornado + knockup provides free positioning time for Jinx. Anti-dive core.'),
  ('nami',         'lucian',       94, 'Nami E empowers Lucian passive proc with extra bounce on every auto. Top-tier lane.'),
  ('nami',         'miss-fortune', 82, 'Both have AoE CC. Nami tidal wave into MF Bullet Time is a teamfight nuke.'),
  ('nami',         'samira',       86, 'Nami tidal wave sets up Samira style stacks and ult window instantly.'),
  ('soraka',       'vayne',        86, 'Global heal compensates for Vayne''s entire early vulnerability window.'),
  ('soraka',       'jinx',         82, 'Soraka sustain lets Jinx farm safely until she hyperscales.'),
  ('soraka',       'kog-maw',      88, 'Keeps the extremely immobile Kog''Maw alive so he can reach his range power spike.'),
  ('blitzcrank',   'jinx',         72, 'Blitz hook into Jinx kill confirms and resets create snowball lane pressure.'),
  ('blitzcrank',   'caitlyn',      84, 'Caitlyn trap combos perfectly with Blitz hook. Trapped target into hook is a guaranteed kill.'),
  ('blitzcrank',   'miss-fortune', 78, 'Blitz hook pulls a target out of position for MF''s Q empowered shot.'),
  ('rakan',        'xayah',        100,'Canonical synergy: shared ult, Rakan dash procs Xayah passive. Best duo in the game.'),
  ('rakan',        'kai-sa',       85, 'Rakan''s charm + engage sets up Kai''Sa ult re-engage perfectly.'),
  ('senna',        'lucian',       90, 'Canonical duo. Senna heals safely; both proc each other''s passives from range.'),
  ('senna',        'jinx',         78, 'Senna global heal lets Jinx dive for resets without fear of dying.'),
  ('pyke',         'miss-fortune', 86, 'Pyke execute into MF Bullet Time setup is a teamfight win condition in one combo.'),
  ('pyke',         'draven',       88, 'Both get shared execute gold. High-pressure all-in lane that snowballs fast.'),
  ('yuumi',        'jinx',         92, 'Yuumi attaches to Jinx, effectively making her unkillable while she hyperscales.'),
  ('yuumi',        'vayne',        90, 'Same logic as Jinx — Yuumi turns Vayne into an unkillable late-game monster.'),
  ('yuumi',        'kai-sa',       88, 'Yuumi''s buffs + Kai''Sa mobility creates a self-sufficient killing machine.'),
  ('alistar',      'miss-fortune', 82, 'Alistar WQ combo into MF Bullet Time wins team fights at level 6.'),
  ('alistar',      'tristana',     78, 'Alistar flips, Tristana jumps to clean up. Simple, reliable CC chain.'),
  ('braum',        'caitlyn',      78, 'Braum passive stacks with Caitlyn headshots. Defensive peel for an immobile ADC.'),
  ('braum',        'ashe',         80, 'Both passive procs stack. Ashe slows for Braum to close, Braum slows for Ashe arrow.'),
  ('milio',        'vayne',        88, 'Milio cleanse removes CC from Vayne mid-fight; shield keeps her alive through dives.'),
  ('milio',        'kog-maw',      90, 'Milio cleanse + shield keeps the immobile Kog''Maw alive. His range does the rest.'),
  ('rell',         'miss-fortune', 86, 'Rell magnetic pull groups enemies for MF Bullet Time to shred.'),
  ('rell',         'jinx',         78, 'Rell hard engage lets Jinx sit back and AoE everything in the clustered fight.'),
  ('swain',        'blitzcrank',   82, 'Blitz hooks pull target into Swain drain range. Both benefit from grouped enemies.'),
  ('morgana',      'caitlyn',      80, 'Morgana root chains with Caitlyn traps. Black Shield protects Caitlyn from hard CC.'),
  ('amumu',        'miss-fortune', 90, 'Amumu aoe stun into MF Bullet Time is one of the strongest ults combos in the game.'),
  ('malphite',     'yasuo',        92, 'Malphite unstoppable ult launches Yasuo''s Last Breath for guaranteed kills.'),
  ('malphite',     'miss-fortune', 88, 'Both AOE ults combo. Malphite ult into MF bullet time wins team fights.'),
  ('galio',        'miss-fortune', 82, 'Galio global ult into MF lane fight creates a three-person burst window.'),
  ('zilean',       'vayne',        88, 'Zilean revive lets Vayne take risks she normally can''t. Speed buff helps her kite.'),
  ('bard',         'jinx',         76, 'Bard chimes and stun set up Jinx rocket follow-up; his roams create map-wide pressure.'),
  ('shen',         'vayne',        78, 'Shen taunt + shield buys Vayne the time she needs to stack and kite safely.'),
  ('pantheon',     'jinx',         80, 'Pantheon global ult engage opens up easy AoE cleanup for Jinx.')
) AS s(a_slug, b_slug, score, reason)
JOIN public.champions a ON a.slug = s.a_slug
JOIN public.champions b ON b.slug = s.b_slug
ON CONFLICT (champion_a_id, champion_b_id) DO UPDATE SET
  score         = EXCLUDED.score,
  reason        = EXCLUDED.reason,
  patch_version = EXCLUDED.patch_version;


-- ═══════════════════════════════════════════════════════════════════════════
-- COUNTERS (Patch 7.1f)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO public.counters (champion_id, countered_by_id, severity, reason, patch_version)
SELECT c.id, cb.id, co.severity, co.reason, '7.1f'
FROM (VALUES
  ('soraka',      'blitzcrank', 5, 'Soraka has no escape from Blitz hook. Hooked Soraka is dead. Removes all healing from lane.'),
  ('soraka',      'pyke',       4, 'Pyke hook + execute bypasses Soraka healing. Soraka can''t out-sustain an execute.'),
  ('soraka',      'leona',      4, 'Leona CC lockdown prevents Soraka from healing. Hard all-in wins before she can react.'),
  ('soraka',      'brand',      4, 'Brand passive prevents Soraka healing from mattering. DoT burn overwhelms sustain.'),
  ('soraka',      'xerath',     3, 'Xerath range lets him poke Soraka from outside her silence range safely all game.'),
  ('sona',        'blitzcrank', 5, 'Sona is the easiest hook target in the game — no dash, short range, stands still.'),
  ('sona',        'leona',      5, 'Leona hard engages on Sona before she can react. No escape, no defense.'),
  ('sona',        'pyke',       4, 'Pyke can execute Sona before she can use her passive shield effectively.'),
  ('yuumi',       'blitzcrank', 4, 'Yuumi loses her host to a hook. Stranded Yuumi with no valid attach target is dead.'),
  ('yuumi',       'thresh',     3, 'Thresh hook on the ADC leaves Yuumi without a target to attach to.'),
  ('yuumi',       'morgana',    3, 'Morgana Black Shield only protects the ADC. Yuumi is still vulnerable when detached.'),
  ('janna',       'leona',      4, 'Hard CC chain gives Janna no time to disengage. Her ult can be cancelled by CC.'),
  ('janna',       'blitzcrank', 3, 'Janna has no escape if she''s the hook target. Tornado is too slow to prevent it.'),
  ('lulu',        'blitzcrank', 3, 'If Lulu gets hooked, she needs to use Whimsy defensively and loses offensive value.'),
  ('lulu',        'leona',      3, 'Leona''s all-in is fast enough to kill Lulu before polymorph interrupts it.'),
  ('lux',         'leona',      4, 'Leona dives past Lux root at close range. One full CC chain deletes her.'),
  ('lux',         'blitzcrank', 4, 'Lux has no escape and is easy to hook. Hooked Lux loses the lane.'),
  ('zyra',        'blitzcrank', 4, 'Zyra''s plants reduce her mobility. Easy to hook, plants don''t save her.'),
  ('zyra',        'leona',      3, 'Leona closes too fast for Zyra to place plants effectively in defense.'),
  ('brand',       'blitzcrank', 3, 'Brand is immobile. Hook removes him from his poke range and kills him.'),
  ('nami',        'blitzcrank', 3, 'Nami has no escape from a Blitz hook. Gets hooked, dies, lane is over.'),
  ('vel-koz',     'blitzcrank', 4, 'Vel''Koz is completely immobile. Blitz hook is almost always a kill.'),
  ('leona',       'janna',      3, 'Janna ult pushes Leona away and knocks everyone up, completely negating her engage.'),
  ('leona',       'lulu',       3, 'Lulu polymorph cancels Leona''s engage entirely. Times right, it shuts her down.'),
  ('alistar',     'nautilus',   3, 'Nautilus hook into CC chain counters Alistar''s combo timing completely.'),
  ('blitzcrank',  'thresh',     3, 'Thresh can hook targets that Blitz misses and offers more CC variety.'),
  ('pyke',        'leona',      3, 'Leona is tankier than Pyke can execute. His hook is less reliable than hers.'),
  ('pyke',        'alistar',    4, 'Alistar CC chain stuns Pyke before he can execute. Alistar resists Pyke''s kit.'),
  ('nilah',       'leona',      4, 'Nilah is melee, giving Leona a trivially easy engage target with no escape tool.'),
  ('bard',        'leona',      3, 'Bard has no hard escape if caught by Leona''s engage chain before he can roam away.'),
  ('milio',       'blitzcrank', 3, 'Milio is stationary and easy to hook before he can shield his carry.')
) AS co(c_slug, cb_slug, severity, reason)
JOIN public.champions c ON c.slug = co.c_slug
JOIN public.champions cb ON cb.slug = co.cb_slug
ON CONFLICT (champion_id, countered_by_id) DO UPDATE SET
  severity      = EXCLUDED.severity,
  reason        = EXCLUDED.reason,
  patch_version = EXCLUDED.patch_version;
